---

version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*os.File).WriteString
        - (*os.Process).Kill
        - (*github.com/roddhjav/apparmor.d/pkg/paths.Process).Kill
        - (*bufio.Writer).Flush
        - (*bufio.Writer).WriteString
        - (*github.com/roddhjav/apparmor.d/pkg/paths.Path).Chmod
        - (*github.com/roddhjav/apparmor.d/pkg/paths.Path).Remove
        - (*github.com/roddhjav/apparmor.d/pkg/paths.Path).RemoveAll
        - (*github.com/roddhjav/apparmor.d/cmd/aa-flatpak.FileWatcher).Close
        - os.Remove
        - path/filepath.WalkDir
    staticcheck:
      checks:
        - all
  exclusions:
    paths:
      - internal/
      - tests/cmd/
