# apparmor.d - Full set of apparmor profiles
# Copyright (C) 2021-2024 Alexandre Pujol <alexandre@pujol.io>
# SPDX-License-Identifier: GPL-2.0-only

# Project information
site_name: AppArmor.d
site_url: https://apparmor.pujol.io
site_author: Alexandre Pujol
site_description: >-
  Full set of AppArmor profiles

# Repository
repo_name: roddhjav/apparmor.d
repo_url: https://github.com/roddhjav/apparmor.d
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2021-2025 Alexandre Pujol

# Configuration
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: brown
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    view: material/file-eye-outline
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - assets/stylesheets/extra.css

# Plugins
plugins:
  - privacy
  - search
  - offline:
      enabled: !ENV [MKDOCS_OFFLINE, true]
  - git-revision-date-localized:
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, true]
      enable_creation_date: true
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - git-committers:
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, true]
      token: !ENV [MKDOCS_GIT_COMMITTERS_APIKEY]
      repository: roddhjav/apparmor.d
      branch: main

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/roddhjav
    - icon: fontawesome/brands/github
      link: https://github.com/roddhjav/apparmor.d
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/roddhjav/apparmor.d
    - icon: fontawesome/solid/up-right-from-square
      link: https://pujol.io

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - docs/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Home:
    - index.md
    - Getting Started:
      - overview.md
      - concepts.md
      - install.md
      - configuration.md
      - usage.md
      - report.md
    - Advanced:
      - variables.md
      - enforce.md
      - full-system-policy.md
    - Troubleshooting:
      - issues.md
      - recovery.md
  - Development:
    - development/index.md
    - development/roadmap.md
    - Profiles:
      - development/workflow.md
      - development/guidelines.md
      - development/abstractions.md
      - development/internal.md
      - development/directives.md
      - development/dbus.md
      - development/recommendations.md
    - Packages:
      - development/build.md
    - Tests:
      - development/tests.md
      - development/vm.md
      - development/integration.md
      - development/autopkgtest.md
