# Upstream Apparmor ships with a few profiles that can conflict with apparmor.d
# This file keeps track of them and allow aa-install to overwrite them by our own.
#
# They can be multiple justification for keeping our profiles instead of the
# upstream ones, they are listed below. It is more and more common that these
# profiles simply present incompatibilies with apparmor.d in general.
#
# File format: one profile name by line.

# Overwrite unconfined upstream profiles that only allow userns
brave
brave-browser-stable
chrome
chromium
cockpit-desktop
code
crun
deezer-desktop
element-desktop
epiphany
firefox
flatpak
foliate
font-manager
lens-desktop
loupe
msedge
mullvad
nautilus
opera
os-prober
plasmashell
podman
qutebrowser
runc
signal-desktop
slirp4netns
steam
systemd-coredump
thunderbird
virtiofsd

# Overwrite upstreamed profiles, our local version may be more up to date
glycin.bwrap
glycin.loaders
unix-chkpwd

# Overwrite profiles with some incompatibilities (peer name, variable, abstractions) with apparmor.d
fusermount3
guestfs-tools # Profile provided by the guestfs-tools package, has issues.
hostname
lsblk
lsusb
openvpn
pollinate
remmina
systemd-detect-virt
transmission
usr.bin.man
usr.bin.papers
usr.bin.passt
usr.lib.libreoffice.program.soffice.bin # Conflict due to a missing abi version.
wg-quick
who
wpa_supplicant
Xorg

# Overwrite profiles that are not strict or are not maintained well enough
usr.bin.firefox
usr.bin.swtpm
usr.bin.wsdd
usr.libexec.geoclue
usr.sbin.cups-browsed
usr.sbin.cupsd
usr.sbin.rsyslogd
