# Apparmor 4.0 and over ships a few profiles that can conflict with apparmor.d
# This file keeps track of them and allow aa-install to replace them by our own.
# File format: one profile name by line.

# Overwrite unconfined upstream profiles that only allow userns
brave
brave-browser-stable
chrome
chromium
cockpit-desktop
code
crun
deezer-desktop
element-desktop
epiphany
firefox
flatpak
foliate
font-manager
lens-desktop
loupe
msedge
mullvad
nautilus
opera
os-prober
plasmashell
podman
qutebrowser
runc
signal-desktop
slirp4netns
steam
systemd-coredump
thunderbird
virtiofsd

# Overwrite upstreamed profiles, our local version may be more up to date
unix-chkpwd

# Overwrite some profiles present both in apparmor and apparmor.d
# They can be multiple justification for keeping our profiles here:
# - Keep ours:
#    - If we/they use abstractions, tunable, rules, and integration with apparmor.d that would break if using the upstream profile
#    - If upstream profile is based on apparmor.d version, apparmor.d version will be more up to date
#    - When our profile is more restricted
# - Drop ours: when upstream profiles is better
#
# It is more and more common that these profiles simply present incompatibilies with apparmor.d in general.
fusermount3
glycin.bwrap
glycin.loaders
lsblk
lsusb
openvpn
pollinate
remmina
systemd-detect-virt # Missing integration with @{p_systemd}
transmission
usr.bin.man
usr.bin.papers
usr.bin.passt
wg-quick
who
wpa_supplicant

# Cannot be used as libreoffice handle this path. Conflict with apparmor.d due to a missing abi version.
usr.lib.libreoffice.program.soffice.bin

# apparmor.d version are way more restricted
usr.bin.firefox
usr.bin.swtpm
usr.bin.wsdd
usr.libexec.geoclue
usr.sbin.cups-browsed
usr.sbin.cupsd
usr.sbin.rsyslogd

# Profile provided by the guestfs-tools package, has issues.
guestfs-tools
