// apparmor.d - Full set of apparmor profiles
// Copyright (C) 2021-2026 Alexandre Pujol <alexandre@pujol.io>
// SPDX-License-Identifier: GPL-2.0-only

package configure

import (
	"fmt"
	"maps"
	"regexp"
	"slices"
	"strings"

	"github.com/roddhjav/apparmor.d/pkg/paths"
	"github.com/roddhjav/apparmor.d/pkg/tasks"
)

var (
	tunables = map[string]string{
		// Set systemd profiles name
		"sd":           "sd",
		"sdu":          "sdu",
		"systemd_user": "systemd-user",
		"systemd":      "systemd",

		// With FSP on apparmor 4.1+, the dbus profiles don't get stacked as they
		"dbus_system":  "dbus-system",
		"dbus_session": "dbus-session",

		// Update name of stacked profiles
		"apt_news":               "",
		"colord":                 "",
		"e2scrub_all":            "",
		"e2scrub":                "",
		"fprintd":                "",
		"fwupd":                  "",
		"fwupdmgr":               "",
		"geoclue":                "",
		"irqbalance":             "",
		"logrotate":              "",
		"ModemManager":           "",
		"nm_priv_helper":         "",
		"pcscd":                  "",
		"polkitd":                "",
		"power_profiles_daemon":  "",
		"rsyslogd":               "",
		"systemd_coredump":       "",
		"systemd_homed":          "",
		"systemd_hostnamed":      "",
		"systemd_importd":        "",
		"systemd_initctl":        "",
		"systemd_journal_remote": "",
		"systemd_journald":       "",
		"systemd_localed":        "",
		"systemd_logind":         "",
		"systemd_machined":       "",
		"systemd_networkd":       "",
		"systemd_oomd":           "",
		"systemd_resolved":       "",
		"systemd_rfkill":         "",
		"systemd_timedated":      "",
		"systemd_timesyncd":      "",
		"systemd_userdbd":        "",
		"upowerd":                "",
	}
)

const (
	// fspRel is the full system policy group, relative to aa.Magic.
	fspRel = "groups/_full"

	// profilesRel is the profile name tunable, relative to aa.Magic.
	profilesRel = "tunables/multiarch.d/profiles"

	// fspDropinRel is the generated profile name overrides, relative to aa.Magic.
	fspDropinRel = "tunables/multiarch.d/profiles.d/fsp"
)

type FullSystemPolicy struct {
	tasks.BaseTask
	enabled  bool
	tunables *paths.Path
}

// NewFullSystemPolicy creates a new FullSystemPolicy task. When enabled, it
// keeps the full system policy group and overrides the profile names read
// from tunables. Otherwise, it removes the group.
func NewFullSystemPolicy(enabled bool, tunables *paths.Path) *FullSystemPolicy {
	return &FullSystemPolicy{
		BaseTask: tasks.BaseTask{
			Keyword: "fsp",
			Msg:     "Configure AppArmor for full system policy",
		},
		enabled:  enabled,
		tunables: tunables,
	}
}

func (p FullSystemPolicy) Apply() ([]string, error) {
	res := []string{}
	if !p.enabled {
		return res, p.RootApparmor.Join(fspRel).RemoveAll()
	}

	// Override the profile names for FSP, the tunable itself is not ours
	in, err := p.tunables.ReadFileAsString()
	if err != nil {
		return res, err
	}
	var out strings.Builder
	out.WriteString("# apparmor.d - Full set of apparmor profiles\n")
	out.WriteString("# Generated by aa-install for full system policy, do not edit.\n\n")
	for _, varname := range slices.Sorted(maps.Keys(tunables)) {
		profile := tunables[varname]
		if profile == "" {
			m := regexp.MustCompile(`@\{p_` + varname + `}=([^\s]+)`).FindStringSubmatch(in)
			if m == nil {
				continue
			}
			profile = "{" + m[1] + ",sd//&" + m[1] + "," + m[1] + "//&sd}"
		}
		fmt.Fprintf(&out, "@{p_%s}:=%s\n", varname, profile)
	}
	dropin := p.RootApparmor.Join(fspDropinRel)
	if err := dropin.Parent().MkdirAll(); err != nil {
		return res, err
	}
	return append(res, dropin.String()), dropin.WriteFile([]byte(out.String()))
}
