# Debian specific definition
apparmor.d/groups/apt
share/apparmor/flags.d/10-debian.conf
share/apparmor/ignore.d/10-debian.conf

# Fedora specific definition
apparmor.d/groups/dnf
share/apparmor/flags.d/10-fedora.conf
share/apparmor/ignore.d/10-fedora.conf

# Ubuntu specific definition 
apparmor.d/groups/ubuntu
apparmor.d/tunables/alias.d/coreutils
apparmor.d/tunables/alias.d/uutils
share/apparmor/flags.d/10-ubuntu.conf
share/apparmor/ignore.d/10-ubuntu.conf

# OpenSUSE specific definition
apparmor.d/groups/suse
share/apparmor/flags.d/10-opensuse.conf
share/apparmor/ignore.d/10-opensuse.conf
