# Archlinux specific
apparmor.d/groups/pacman
share/apparmor/flags.d/10-arch.conf
share/apparmor/ignore.d/10-arch.conf
share/libalpm

# Fedora specific definition
apparmor.d/groups/dnf
share/apparmor/flags.d/10-fedora.conf
share/apparmor/ignore.d/10-fedora.conf

# Ubuntu specific definition 
apparmor.d/groups/ubuntu
share/apparmor/flags.d/10-ubuntu.conf
share/apparmor/ignore.d/10-ubuntu.conf

# OpenSUSE specific definition
apparmor.d/groups/suse
share/apparmor/flags.d/10-opensuse.conf
share/apparmor/ignore.d/10-opensuse.conf

# Profiles provided by they own package
chronyd
# libvirt
# virt-aa-helper
