# Common ignore file for all distributions
# File format: one ignore by line, it can be a profile name or a directory to ignore

# Profiles here are not shipped in the apparmor.d package while profiles in 
# share/apparmor/ignore.d are not enabled on the target host.

# Work in progress and conflicts
apparmor.d/groups/cosmic
apparmor.d/namespaces/flatpak

