# Archlinux specific
apparmor.d/groups/pacman
share/apparmor/flags.d/10-arch.conf
share/apparmor/ignore.d/10-arch.conf
share/libalpm

# Debian specific definition
apparmor.d/groups/apt
share/apparmor/flags.d/10-debian.conf
share/apparmor/ignore.d/10-debian.conf

# Fedora specific definition
apparmor.d/groups/dnf

# Ubuntu specific definition
apparmor.d/groups/ubuntu
share/apparmor/flags.d/10-ubuntu.conf
share/apparmor/ignore.d/10-ubuntu.conf

# Profiles provided by they own package
libvirt
virt-aa-helper
