# Common ignore file for all distributions
# File format: one ignore by line, it can be a profile name or a directory to ignore

# Contains profiles and configuration for full system confinement, only included
# when built with 'just fsp'
apparmor.d/groups/_full

# Provided by other packages
man

# Breaks POLA
apparmor.d/groups/code
claude

# Kernel panic
# podman
# conmon
# crun
# toolbox

# Work in progress profiles
aa-autodep
aa-logprof
aa-mergeprof
aa-remove-unknown
apparmor.d/groups/steam
dunst
plasma-discover
