# Profile modes for Arch based distributions
# File format: one profile mode by line using the format: '<profile> <mode>'

aurpublish complain
makepkg complain
mkinitcpio complain
packagekitd complain # support on Arch is not complete
pacman complain
