# apparmor.d - Full set of apparmor profiles
# Copyright (C) 2023 Alexandre Pujol <alexandre@pujol.io>
# SPDX-License-Identifier: GPL-2.0-only

abi <abi/3.0>,

include <tunables/global>

@{exec_path} = /usr/share/netplan/netplan.script
profile netplan.script @{exec_path} {
  include <abstractions/base>

  @{exec_path} mr,

  @{lib}exec/netplan/generate rix,

  /usr/share/netplan/{,**} r,

  include if exists <local/netplan.script>
}