# apparmor.d - Full set of apparmor profiles
# Copyright (C) 2026 Alexandre Pujol <alexandre@pujol.io>
# SPDX-License-Identifier: GPL-2.0-only

abi <abi/5.0>,

include <tunables/global>

profile flatpak.install flags=(attach_disconnected) {
  include <abstractions/base>
  include <abstractions/consoles>
  include <abstractions/nameservice-strict>

  /app/bin/*     ix,
  @{bin}/**      ix,
  @{lib}/**      ix,

  /app/{,**} mr,
  /app/extra/{,**} rw,

  include if exists <local/flatpak.install>
}

# vim:syntax=apparmor
